# maysics.calc模块使用说明

calc模块包含七个函数

|名称|作用|
|---|---|
|lim|极限|
|ha|哈密顿算符|
|grad|梯度|
|nebla_dot|nebla算子点乘|
|nebla_cross|nebla算子叉乘|
|laplace|拉普拉斯算子|
|inte|积分|

<br></br>
## 求极限：lim
lim(f, x0, acc=0.01, method='both')
<br>求函数```f```在```acc```的误差下，$x\rightarrow x_{0}$的函数值
<br>```method```可选'both'、'+'、'-'，分别表示双边极限、右极限、左极限

### DEMO 1-1：求函数$y=\frac{sin(x)}{x}$中$x\rightarrow0$时的值

In [1]:
import maysics as ms
import numpy as np

def f(x):
    return np.sin(x) / x

ms.calc.lim(f, 0)

0.9999833334166665

<br></br>
## 哈密顿算符：ha
哈密顿算符：$\hat{H}=-\frac{\hbar^{2}{\nabla^{2}}}{2m}+U$

<br>ha(f, m, U, acc=0.1)
<br>求函数```f```在```acc```误差下，粒子质量为```m```，势能为```U```时，通过哈密顿算符生成的新函数
<br>```f```需要以数组作为输入（不能是数）
<br>```U```是常数或函数

### DEMO 2-1：求函数$y=x$通过哈密顿算符生成的新函数

In [2]:
import maysics as ms

def f(x):
    return x

# m=1, U=2
f_new = ms.calc.ha(f, 1, 2)

# 输出x=(1, 2, 3)时的函数值
f_new([1, 2, 3])

array([2., 4., 6.])

<br></br>
## 梯度：grad
grad(f, x, acc=0.1)
<br>在acc误差下计算函数f在x处的梯度

### DEMO 3-1：求函数$y=x^{2}+y^{2}$在点$(3, 3)$处的梯度

In [3]:
import maysics as ms

def f(x):
    return x[0]**2 + x[1]**2

ms.calc.grad(f, [3, 3])

array([6., 6.])

<br></br>
## nebla算子：nebla_dot和nebla_cross
nebla_dot用于点乘矢量函数：$\nabla\centerdot\vec{f}$
<br>nebla_dot(f, x, acc=0.1)

<br>nebla_cross用于叉乘矢量函数：$\nabla\times\vec{f}$（此时函数f的输出必须是三维的）
<br>nebla_cross(f, x, acc=0.1)
<br>用法类似grad函数

### DEMO 4-1：$\nabla\centerdot\vec{f}$，$\vec{f}=x^{2}\vec{i}+y^{2}\vec{j}+z^{2}\vec{k}$在点$(1,1,1)$的函数值

In [4]:
import maysics as ms

def f(x):
    return x[0]**2, x[1]**2, x[2]**2

ms.calc.nebla_dot(f, [1, 1, 1])

array([2., 2., 2.])

### DEMO 4-2：$\nabla\times\vec{f}$，$\vec{f}=x^{2}\vec{i}+y^{2}\vec{j}+z^{2}\vec{k}$在点$(1,1,1)$的函数值

In [5]:
import maysics as ms

def f(x):
    return x[0]**2, x[1]**2, x[2]**2

ms.calc.nebla_cross(f, [1, 1, 1])

array([0., 0., 0.])

<br></br>
## 拉普拉斯算子：laplace
$\Delta=\nabla^{2}$

<br>laplace(f, x, acc=0.1)
<br>函数```f```需以一维数组作为输入，且不支持批量输入

### DEMO 5-1：不支持小批量输入函数：$f(x,y,z)=x^{2}+y^{2}+z^{2}$在点$(1,1,1)$的$\Delta f$值

In [6]:
import maysics as ms

def f(x):
    return sum(x**2)

ms.calc.laplace(f, [1,1,1])

6.000000000000137

### DEMO 5-2：支持小批量输入函数：$f(x,y,z)=x^{2}+y^{2}+z^{2}$在点集${(1,1,1),(2,2,2)}$的$\Delta f$值

In [7]:
import maysics as ms

def f(x):
    return (x**2).sum(axis=1)

ms.calc.laplace(f, [[1,1,1],[2,2,2]])

array([6., 6.])

<br></br>
## 定积分：inte
inte(func, area, method='rect', dim=1, args={}, condition=None, param={}, acc=0.1, loop=10000, height=1, random_state=None)
<br>```func```是被积函数
<br>```area```是一个二维数组，表示各个维度的积分范围
<br>```method```可选'rect'和'mc'，分别表示使用矩形法和蒙特卡洛法进行积分，```acc```参数仅对矩形法起作用，```loop```、```height```和```random_state```参数仅对蒙特卡洛法起作用
<br>```dim```参数表示输入函数的维度，默认为一维函数
<br>```args```表示输入函数f除了自变量以外的其他参数
<br>```condition```是条件函数，当```condition```不为None时，只有满足```condition```（即输出为True）的点才会纳入积分范围
<br>```param```表示函数```condition```除了自变量以外的其他参数
<br>```acc```既可以是数类型，也可以是一维数组类型，前者表示各个维度精度一致，后者则可以各个维度精度不同

### 使用矩形法进行定积分
超矩形的大小为：$f(x)\times acc^{dim}$

### DEMO 6-1：求$f(x)=sin(x)$在0到π上的积分

In [8]:
import maysics as ms
import numpy as np

ms.calc.inte(np.sin, [[0, np.pi]])

1.9995479597125976

### DEMO 6-2：求$f(x)=Asin(x)$在0到π上的积分

In [9]:
import maysics as ms
import numpy as np

def f(x, A):
    return A * np.sin(x)

# 取A=2
ms.calc.inte(f, [[0, np.pi]], args={'A':2})

3.999095919425195

### DEMO 6-3：求$f(x)=2sin(x)$在0到π上函数值小于等于1区域的积分

In [10]:
import maysics as ms
import numpy as np

def c(x):
    if 2 * np.sin(x) <= 1:
        return True
    else:
        return False

# 取A=2
ms.calc.inte(np.sin, [[0, np.pi]], condition=c)

0.26471848651129565

### DEMO 6-4：求$f(x,y)=x^{2}+y^{2}$在$x\in[-2,2]$，$y\in[-1,1]$的积分

In [11]:
import maysics as ms

def f(x):
    return x[0]**2 + x[1]**2

ms.calc.inte(f, [[-2, 2], [-1, 1]])

13.360000000000017

### 使用蒙特卡洛法进行定积分
在$area\times height$的超矩形中随机产生loop个散点（注意$height\geq maxf(x)$在area中恒成立）
<br>将$y\leq f(x)$的散点数记为n，则积分$\approx\frac{n}{loop}\times area \times height$
<br>random_state是随机种子

### DEMO 6-5：求f(x)=2sin(x)在0到π上的积分

In [12]:
import maysics as ms
import numpy as np

def f(x):
    return 2 * np.sin(x)

ms.calc.inte(f, [[0, np.pi]], method='mc', height=2)

3.9181943575571903

### DEMO 6-6：求$f(x,y)=x^{2}+y^{2}$在$x\in[-2,2]$，$y\in[-1,1]$的积分

In [13]:
import maysics as ms

def f(x):
    return x[0]**2 + x[1]**2

ms.calc.inte(f, [[-2, 2], [-1, 1]], method='mc', height=5)

13.32